# Generated by Django 4.1 on 2022-08-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="FSSAI_licence",
            field=models.FileField(blank=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="GSTIN_certificate",
            field=models.FileField(blank=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="closing_time",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_time",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="photos",
            field=models.FileField(blank=True, upload_to="media"),
        ),
    ]
