# Generated by Django 4.1 on 2022-08-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_restaurant_verify"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "dish_type",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("main", "Main Course"),
                            ("Fast", "Fast Food"),
                            ("Dessert", "Dessert"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[("veg", "Veg"), ("non", "Nonveg")], max_length=3
                    ),
                ),
                ("photo", models.FileField(upload_to="media")),
                ("description", models.TextField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("f", "Full"), ("h", "Half")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("price_of_dish", models.CharField(max_length=4)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.dish",
                    ),
                ),
            ],
        ),
    ]
