# Generated by Django 4.1 on 2022-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_dish_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="dish_type",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("break", "Break Fast"),
                    ("main", "Main Course"),
                    ("Fast", "Fast Food"),
                    ("Dessert", "Dessert"),
                ],
                max_length=8,
            ),
        ),
    ]
