# Generated by Django 4.1 on 2022-08-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_dish_dish_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="price",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("f", "Full"), ("h", "Half"), ("n", "None")],
                max_length=1,
                null=True,
            ),
        ),
    ]
