# Generated by Django 4.1 on 2022-08-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_remove_price_quantity_alter_price_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="photo",
            field=models.FileField(upload_to="dish"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="FSSAI_licence",
            field=models.FileField(blank=True, upload_to="restaurant/fssai/"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="GSTIN_certificate",
            field=models.FileField(blank=True, upload_to="restaurant/gstin/"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="photos",
            field=models.FileField(blank=True, upload_to="restaurant/photo/"),
        ),
    ]
