# Generated by Django 4.1 on 2022-08-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_alter_dish_photo_alter_restaurant_fssai_licence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="total_rating",
            field=models.IntegerField(default=0),
        ),
    ]
