# Generated by Django 4.1 on 2022-08-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_alter_price_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={},
        ),
    ]
