# Generated by Django 4.1 on 2022-08-05 11:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                (
                    "owner_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("email", models.CharField(max_length=35)),
                ("password", models.CharField(max_length=25)),
                ("opening_time", models.TimeField(blank=True)),
                ("closing_time", models.TimeField(blank=True)),
                ("photo", models.FileField(blank=True, upload_to="media")),
                ("FSSAI_licence", models.FileField(blank=True, upload_to="media")),
                ("GSTIN_certificate", models.FileField(blank=True, upload_to="media")),
                ("verify", models.BooleanField(default=False)),
            ],
        ),
    ]
