# Generated by Django 4.1 on 2022-08-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
