# Generated by Django 4.1 on 2022-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_restaurant_owner_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(max_length=35),
        ),
    ]
