# Generated by Django 4.1 on 2022-08-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_cartitems_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
