# Generated by Django 4.1 on 2022-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_orderdetails_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("deb", "Debit Card"),
                    ("ced", "Credit Card"),
                    ("cod", "Cash on Delivery"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="total_amount",
            field=models.FloatField(),
        ),
    ]
