# Generated by Django 4.1 on 2022-09-01 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_rename_dishesh_orderdetails_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_and_charges', models.FloatField()),
                ('delivery_charges', models.IntegerField(default=25)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('orders', models.ManyToManyField(to='user.orderdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
