# Generated by Django 4.1 on 2022-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='terms_and_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='validity',
            field=models.DateTimeField(blank=True),
        ),
    ]
