# Generated by Django 4.1 on 2022-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_offer_restaurant_alter_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='use',
            field=models.BooleanField(default=False),
        ),
    ]
