# Generated by Django 4.1 on 2022-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_restaurant_fssai_licence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="verify",
            field=models.BooleanField(default=False),
        ),
    ]
