# Generated by Django 4.1 on 2022-08-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_restaurant_total_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ["-price_of_dish"]},
        ),
    ]
