# Generated by Django 4.1 on 2022-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_alter_price_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price_of_dish",
            field=models.IntegerField(default=0),
        ),
    ]
