# Generated by Django 4.1 on 2022-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_orderdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
