# Generated by Django 4.1 on 2022-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_orderdetails_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='dishesh',
            field=models.ManyToManyField(blank=True, to='user.cartitems'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_method',
            field=models.CharField(max_length=10),
        ),
    ]
