# Generated by Django 4.1 on 2022-09-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_orderdetails_price_orderdetails_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='dishesh',
            new_name='dish',
        ),
    ]
