# Generated by Django 4.1 on 2022-09-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_orderdetails_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
