# Generated by Django 4.1 on 2022-09-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_restaurant_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_order_bill_to_pay_alter_order_tax_and_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_in_percentage', models.CharField(max_length=2)),
                ('validity', models.DateTimeField()),
                ('promocode', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('terms_and_condition', models.TextField()),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
