# Generated by Django 4.1 on 2022-09-05 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_restaurant_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0018_offer_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ManyToManyField(blank=True, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
