# Generated by Django 4.1 on 2022-09-05 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_restaurant_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_remove_offer_restaurant_remove_offer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
